import { ACCOUNT_TYPES, INVESTMENT_VEHICLES, YEARS } from "../../constants";


export const initialValues = {
  expenses: [],
  salaries: [],
  other_incomes: [],
  assets: [],
  house_purchases: [],
  scheduled_debts: [],
  other_debts: [],
  transfers: [],
  accounts: [
    {
      name: "Bank accounts",
      account_type: ACCOUNT_TYPES.BANK.value,
      starting_balance: 10000,
      earliest_withdrawal_year: YEARS.START,
      investments: [],
    },
    {
      name: "Investment accounts",
      account_type: ACCOUNT_TYPES.INVESTMENT.value,
      starting_balance: 10000,
      earliest_withdrawal_year: YEARS.START,
      investments: [
        {
          name: INVESTMENT_VEHICLES.STOCKS,
          color: "steelblue",
          anchors: [
            { year: 2025, value: 70 },
            { year: 2030, value: 70 },
            { year: 2035, value: 70 },
            { year: 2040, value: 70 },
            { year: 2045, value: 70 },
            { year: 2050, value: 70 },
            { year: 2055, value: 70 },
            { year: 2060, value: 70 },
            { year: 2065, value: 70 },
            { year: 2070, value: 70 },
          ],
        },
        {
          name: INVESTMENT_VEHICLES.BONDS,
          color: "lightgreen",
          anchors: [
            { year: 2025, value: 30 },
            { year: 2030, value: 30 },
            { year: 2035, value: 30 },
            { year: 2040, value: 30 },
            { year: 2045, value: 30 },
            { year: 2050, value: 30 },
            { year: 2055, value: 30 },
            { year: 2060, value: 30 },
            { year: 2065, value: 30 },
            { year: 2070, value: 30 },
          ],
        },
      ],
    },
    {
      name: "Traditional IRA/401k accounts",
      account_type: ACCOUNT_TYPES.RETIREMENT.value,
      starting_balance: 10000,
      earliest_withdrawal_year: YEARS.RETIREMENT_START,
      investments: [
        {
          name: INVESTMENT_VEHICLES.STOCKS,
          color: "steelblue",
          anchors: [
            { year: 2025, value: 100 },
            { year: 2030, value: 90 },
            { year: 2035, value: 80 },
            { year: 2040, value: 70 },
            { year: 2045, value: 60 },
            { year: 2050, value: 50 },
            { year: 2055, value: 50 },
            { year: 2060, value: 50 },
            { year: 2065, value: 50 },
            { year: 2070, value: 50 },
          ],
        },
        {
          name: INVESTMENT_VEHICLES.BONDS,
          color: "lightgreen",
          anchors: [
            { year: 2025, value: 0 },
            { year: 2030, value: 10 },
            { year: 2035, value: 20 },
            { year: 2040, value: 30 },
            { year: 2045, value: 40 },
            { year: 2050, value: 50 },
            { year: 2055, value: 50 },
            { year: 2060, value: 50 },
            { year: 2065, value: 50 },
            { year: 2070, value: 50 },
          ],
        },
      ],
    },
    {
      name: "Roth IRA/401k accounts",
      account_type: ACCOUNT_TYPES.ROTH_IRA.value,
      starting_balance: 10000,
      earliest_withdrawal_year: YEARS.RETIREMENT_START,
      investments: [
        {
          name: INVESTMENT_VEHICLES.STOCKS,
          color: "steelblue",
          anchors: [
            { year: 2025, value: 100 },
            { year: 2030, value: 90 },
            { year: 2035, value: 80 },
            { year: 2040, value: 70 },
            { year: 2045, value: 60 },
            { year: 2050, value: 50 },
            { year: 2055, value: 50 },
            { year: 2060, value: 50 },
            { year: 2065, value: 50 },
            { year: 2070, value: 50 },
          ],
        },
        {
          name: INVESTMENT_VEHICLES.BONDS,
          color: "lightgreen",
          anchors: [
            { year: 2025, value: 0 },
            { year: 2030, value: 10 },
            { year: 2035, value: 20 },
            { year: 2040, value: 30 },
            { year: 2045, value: 40 },
            { year: 2050, value: 50 },
            { year: 2055, value: 50 },
            { year: 2060, value: 50 },
            { year: 2065, value: 50 },
            { year: 2070, value: 50 },
          ],
        },
      ],
    },
    {
      name: "529 accounts",
      account_type: ACCOUNT_TYPES.FIVE_TWO_NINE.value,
      starting_balance: 10000,
      earliest_withdrawal_year: YEARS.START,
      investments: [
        {
          name: INVESTMENT_VEHICLES.STOCKS,
          color: "steelblue",
          anchors: [
            { year: 2025, value: 70 },
            { year: 2030, value: 60 },
            { year: 2035, value: 50 },
            { year: 2040, value: 50 },
            { year: 2045, value: 50 },
            { year: 2050, value: 50 },
            { year: 2055, value: 50 },
            { year: 2060, value: 50 },
            { year: 2065, value: 50 },
            { year: 2070, value: 50 },
          ],
        },
        {
          name: INVESTMENT_VEHICLES.BONDS,
          color: "lightgreen",
          anchors: [
            { year: 2025, value: 30 },
            { year: 2030, value: 40 },
            { year: 2035, value: 50 },
            { year: 2040, value: 50 },
            { year: 2045, value: 50 },
            { year: 2050, value: 50 },
            { year: 2055, value: 50 },
            { year: 2060, value: 50 },
            { year: 2065, value: 50 },
            { year: 2070, value: 50 },
          ],
        },
      ],
    },
  ],
  investment_vehicles: [
    {
      name: INVESTMENT_VEHICLES.STOCKS,
      aagr: 6.55,
      dynamic_mean: 7.7,
      dynamic_std_dev: 11.75,
    },
    {
      name: INVESTMENT_VEHICLES.BONDS,
      aagr: 3.52,
      dynamic_mean: 3.9,
      dynamic_std_dev: 8.55,
    },
  ],
};
