version: "3.8" # Ensure the version is at least 3.8

services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
      platforms:
        - linux/amd64
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      args:
        ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      HOST: 0.0.0.0
      PORT: 3000
    command: npm start
