version: "3.8"  # Ensure the version is at least 3.8

services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
      platforms:
        - linux/amd64
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      platforms:
        - linux/amd64
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
