name: Deploy Backend

inputs:
  tag:
    description: Docker image tag
    required: false

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to Cloud Run
      run: |
        IMAGE_TAG=${{ inputs.tag && inputs.tag || github.sha }}
        gcloud run deploy backend-service \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend/backend:$IMAGE_TAG \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
